version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core:v4.23.1
    # image: teddysun/v2ray
    container_name: v2ray
    restart: always
    volumes:
      - /home/v2cli/v2ray:/etc/v2ray/
    ports:
      - "8081:8081"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - v2ray
    volumes:
      - /home/v2cli/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"

  v2cli:
    image: drice64/v2cli:v1
    container_name: v2cli
    restart: always
    depends_on:
      - v2ray
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/v2cli/v2ray:/etc/v2ray/
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      SET_MUL: ${SET_MUL}
      UPDATE_TIME: ${UPDATE_TIME}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M

  sss:
    image: drice64/sss:client
    container_name: sss
    restart: always
    network_mode: "host"
    environment:
      STATUS_ADDRESS: ${STATUS_ADDRESS}
      STATUS_USER: ${STATUS_USER}

