version: "3"
services:
  xray:
    image: teddysun/xray
    container_name: xray
    restart: always
    volumes:
      - /home/xray:/etc/xray/
    ports:
      - "443:443"
      - "8000:443"
      - "8088:443"
      - "8443:443"
    entrypoint: "xray -confdir /etc/xray/conf.d"

  v2cli:
    image: drice64/v2cli:v4
    container_name: v2cli
    restart: always
    depends_on:
      - xray
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xray:/etc/xray/
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      SET_MUL: ${SET_MUL}
      UPDATE_TIME: ${UPDATE_TIME}

