version: "3"
services:
  v2ray:
    image: v2fly/v2fly-core:v4.23.1
    container_name: v2ray
    volumes:
      - /home/v2muser/v2ray:/etc/v2ray/
    ports:
      - "8081:8081"

  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    depends_on:
      - v2ray
    volumes:
      - /home/v2muser/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"

  v2muser:
    build: ./v2muser
    container_name: v2muser
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/v2muser/v2ray:/etc/v2ray/

