version: "3"
services:
  v2ray:
    # image: v2fly/v2fly-core:v4.23.1
    image: teddysun/v2ray
    container_name: v2ray
    restart: always
    volumes:
      - /home/v2cli/v2ray:/etc/v2ray/
    ports:
      - "8081:8081"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - v2ray
    volumes:
      - /home/v2cli/nginx:/etc/nginx/conf.d/
 
    ports:
      - "80:80"
      - "443:443"

  v2cli:
    image: drice64/v2cli:v1
    container_name: v2cli
    restart: always
    depends_on:
      - v2ray
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/v2cli/v2ray:/etc/v2ray/
    env_file: ./v2cli.env

  sss:
    image: drice64/sss:client
    container_name: sss
    restart: always
    network_mode: "host"
    env_file: ./sss.env

