version: "3"
services:
  v2ray:
    image: teddysun/v2ray
    container_name: v2ray
    restart: always
    volumes:
      - /home/v2cli/v2ray:/etc/v2ray/

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - v2ray
    volumes:
      - /home/v2cli/nginx:/etc/nginx/conf.d/
    ports:
      - "8088:443"

  v2cli:
    image: drice64/v2cli:v1
    container_name: v2cli
    restart: always
    depends_on:
      - v2ray
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/v2cli/v2ray:/etc/v2ray/
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      SET_MUL: ${SET_MUL}
      UPDATE_TIME: ${UPDATE_TIME}
