version: "3"
services:
  v2ray:
    image: v2fly/v2fly-core:v4.23.1
    container_name: v2ray
    volumes:
      - /home/v2cli/v2ray:/etc/v2ray/
    ports:
      - "8081:8081"

  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    depends_on:
      - v2ray
    volumes:
      - /home/v2cli/nginx:/etc/nginx/conf.d/
 
    ports:
      - "80:80"
      - "443:443"

  v2cli:
    build: ./v2cli
    container_name: v2cli
    depends_on:
      - v2ray
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/v2cli/v2ray:/etc/v2ray/
    env_file: ./v2cli.env

